### ISSUE TITLE
404 page not built correctly

### ISSUE THREAD

**Issue by We-Gold** [dc7290/astro-fonts-next#50]
My project has a custom 404 page (just a `404.astro`) file, but with this integration active, it fails to build with the following error:

```
ENOENT: no such file or directory, open '/home/<my-username>/code/<my-project>/dist/404/index.html'
```

_`<my-project>` and `<my-username>` are placeholders, not part of the actual error output._

When I remove the 404 page, it works correctly.

**Comment by We-Gold** [comment]
#51

**Comment by dc7290** [comment]
@We-Gold 

Thanks for reporting the issue, and creating the PR!
